apiVersion: v1
kind: Template
metadata:
  name: indy-container-template
labels:
  template: "indy-container-template"
parameters:
- name: TARBALL_URL
  displayName: tarball url env var
  required: true
  value: ''
- name: DATA_TARBALL_URL
  displayName: data tarball url env var
  required: true
  value: ''
- name: INDY_VERSION
  displayName: indy app version
  required: false
  value: ''
objects:
- kind: "BuildConfig"
  apiVersion: "v1"
  metadata:
    labels:
      app: "indy-binary-publish"
      build: "indy-binary-publish"
    name: "indy-binary-publish"
  spec:
    output:
      pushSecret:
        name: quaydotio-nosbot
      to:
        kind: DockerImage
        name: quay.io/factory2/indy:latest
    runPolicy: Serial
    source:
      contextDir: indy
      git:
        ref: "master"
        uri: "https://github.com/Commonjava/commonjava-images.git"
    strategy:
      dockerStrategy:
        noCache: true
        env:
          - name: "tarball_url"
            value: "${TARBALL_URL}"
          - name: "data_tarball_url"
            value: "${DATA_TARBALL_URL}"