apiVersion: v1
kind: Template
metadata:
  name: indy-container-template
labels:
  template: "indy-container-template"
parameters:
- name: NAME
  displayName: Short unique identifier for the templated instances.
  required: true
  value: "indy-container"
- name: INDY_GIT_REPO
  displayName: indy Git repo URL
  description: Default indy Git repo URL in which to run dev tests against
  required: true
  value: https://github.com/Commonjava/indy.git
- name: INDY_GIT_BRANCH
  displayName: indy Git repo ref
  description: Default indy Git repo ref in which to run dev tests against
  required: true
  value: master
- name: INDY_IMAGESTREAM_NAME
  displayName: ImageStream name of the resulting image
  required: true
  value: indy-binary
- name: INDY_IMAGE_TAG
  displayName: Tag of resulting image
  required: true
  value: latest
- name: TARBALL_URL
  displayName: tarball url env var
  required: true
  value: ''
- name: DATA_TARBALL_URL
  displayName: data tarball url env var
  required: true
  value: ''
- name: INDY_IMAGESTREAM_NAMESPACE
  displayName: Namespace of ImageStream for indy container images
  required: false
- name: INDY_VERSION
  displayName: indy app version
  required: false
  value: ''
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: "${INDY_IMAGESTREAM_NAME}"
    labels:
      app: "${NAME}"
- kind: "BuildConfig"
  apiVersion: "v1"
  metadata:
    labels:
      app: "${NAME}"
      build: "${NAME}"
    name: "${NAME}"
  spec:
    output:
      to:
        kind: "ImageStreamTag"
        name: "${INDY_IMAGESTREAM_NAME}:${INDY_IMAGE_TAG}"
        namespace: "${INDY_IMAGESTREAM_NAMESPACE}"
      #pushSecret:
        #name: quaydotio-nosbot
      #to:
        #kind: DockerImage
        #name: quay.io/factory2/indy:latest
    runPolicy: Serial
    source:
      contextDir: indy
      git:
        ref: "master"
        uri: "https://github.com/Commonjava/commonjava-images.git"
    strategy:
      dockerStrategy:
        noCache: true
        env:
          - name: "tarball_url"
            value: "${TARBALL_URL}"
          - name: "data_tarball_url"
            value: "${DATA_TARBALL_URL}"