apiVersion: v1
kind: Template
metadata:
  name: service-container-template
labels:
  template: "service-container-template"
parameters:
- name: NAME
  displayName: Short unique identifier for the templated instances.
  required: true
  value: "sidecar-container"
- name: SVC_VERSION
  displayName: service app version
  required: false
  value: ''
- name: BUILD_URL
  displayName: url of service jenkins build with artifact
  required: true
  value: ''
- name: APP_JAR_NAME
  displayName: artifact jar file name
  required: true
  value: ''
- name: QUAY_TAG
  displayName: tag to push to quay
  required: false
  value: 'latest'
objects:
- kind: "BuildConfig"
  apiVersion: "build.openshift.io/v1"
  metadata:
    labels:
      app: "${NAME}-publish"
      build: "${NAME}-publish"
    name: "${NAME}-publish"
  spec:
    output:
      pushSecret:
        name: quaydotio-nosbot
      to:
        kind: DockerImage
        name: "quay.io/factory2/${NAME}:${QUAY_TAG}"
    runPolicy: Serial
    source:
      contextDir: service
      git:
        ref: "master"
        uri: "https://github.com/Commonjava/commonjava-images.git"
    strategy:
      dockerStrategy:
        noCache: true
        env:
          - name: "build_url"
            value: "${BUILD_URL}"
          - name: "app_jar_url"
            value: "${APP_JAR_URL}"